# Generated by Django 5.0.3 on 2024-03-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddreess',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
